### ISSUE TITLE
Migrate to Jetpack Compose

### ISSUE THREAD

**Issue by mars885** [mars885/gamedge#100]
Jetpack Compose is the new UI framework for Android that is going to replace the current one in the near future.

**Comment by mahmoud-abdallah863** [comment]
I agree.
Do you have a plan to migrate to jetpack compose? I'm happy to help with that.

**Comment by mars885** [comment]
The migration started a couple of months ago. You can track the progress on the [separate branch](https://github.com/mars885/gamedge/tree/feature/migrate-to-compose).
