### ISSUE TITLE
The project is using an incompatible version (7.0.0-beta05) of the Android Gradle plugin.

### ISSUE THREAD

**Issue by pesjak** [mars885/gamedge#120]
I'm trying to build the project with new Android Studio (Arctic Fox), but it says (The project is using an incompatible version (7.0.0-beta05) of the Android Gradle plugin.), and If I upgrade it manually Hilt doesn't work properly, I keep getting` @HiltAndroidApp base class must extend Application`, tried cleaning the project, invalidate cache and restart but no success.

**Comment by mars885** [comment]
Dependencies have been updated. You can now compile it using the AS Arctic Fox. Let me know in case you have problems.
