### ISSUE TITLE
Preload images inside the image viewer screen

### ISSUE THREAD

**Issue by mars885** [mars885/gamedge#141]
The `ViewPager2` class has the method `setOffscreenPageLimit` that allows to preload a specified number of items on either side.

Before the Jetpack Compose migration, it was [used](https://github.com/mars885/gamedge/blob/94c7fdf93965c5126f1041408d238e6e32ad8e6e/feature-image-viewer/src/main/java/com/paulrybitskyi/gamedge/feature/image/viewer/widgets/ImageViewerView.kt#L89) to preload images inside the image viewer screen.

However, the Accompanist's analogue of the `ViewPager2`, does not currently support that. Consider adding it as soon as support for this feature is released.

The [issue to track](https://github.com/google/accompanist/issues/899) on the Accompanist's side.

**Comment by TemMax** [comment]
+.
This feature will be very useful when need to transform pages. For example, using translationX. Now we can't do this because composable will be removed from composition due to scroll.
